package com.nexters.custom;

public enum CityName {
	   SEOUL, INCHEON, GYEONGGI_DO, GANGWON_DO, CHUNGCHEONGNAM_DO, SEJONG, DAEJEON, CHUNGCHEONGBUK_DO,
	   JEOLLABUK_DO, JEOLLANAM_DO, GWANGJU, JEJU, GYEONGBUK, DAEGU, ULSAN, GYEONGSANGNAM_DO, BUSAN
	}